info:
  log_file: "./LOGS/info.log"
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
  maxBytes: 104857600  # 100 MB
  backupCount: 20

error:
  log_file: "./LOGS/error.log"
  level: "ERROR"
  format: "%(asctime)s - %(levelname)s - %(message)s"
  maxBytes: 104857600  # 100 MB
  backupCount: 20





